// Sample data for services in Mieres, Asturias
export const serviciosData = [
  {
    id: "1",
    title: "Moda Astur",
    category: "Productos",
    subcategory: "Ropa y complementos",
    description:
      "Tienda de moda con las últimas tendencias en ropa y complementos para toda la familia. Marcas nacionales e internacionales a precios competitivos.",
    imagePath: "https://images.unsplash.com/photo-1567401893414-76b7b1e5a7a5?w=800",
    badge: "Destacado",
    price: "Varios",
    location: "Mieres",
    phone: "+34 985 123 456",
    whatsapp: "+34985123456",
    website: "www.modaastur.es",
    email: "info@modaastur.es",
    address: "Calle Manuel Llaneza 15, Mieres",
    coordinates: { lat: 43.2505, lng: -5.7752 },
    verified: true,
    isNew: false,
    publishedAt: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000), // 15 días atrás
    userId: "user-1",
  },
  {
    id: "2",
    title: "Electro Turón",
    category: "Productos",
    subcategory: "Electrónica",
    description:
      "Tienda de electrodomésticos y electrónica con las mejores marcas y servicio técnico incluido. Especialistas en soluciones para el hogar y pequeños electrodomésticos.",
    imagePath: "https://images.unsplash.com/photo-1550009158-9ebf69173e03?w=800",
    badge: "Destacado",
    price: "Varios",
    location: "Turón",
    phone: "+34 985 234 567",
    whatsapp: "+34985234567",
    website: "electroturon.es",
    email: "info@electroturon.es",
    address: "Avenida Principal 28, Turón, Mieres",
    coordinates: { lat: 43.2102, lng: -5.7549 },
    verified: true,
    isNew: false,
    publishedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000), // 5 días atrás
    userId: "user-2",
  },
  {
    id: "3",
    title: "Pastelería Dulce Carbón",
    category: "Restaurantes",
    subcategory: "Pastelería",
    description: "Deliciosos dulces tradicionales asturianos elaborados artesanalmente. Especialistas en casadielles, carbayones y moscovitas. Pasteles personalizados para celebraciones.",
    imagePath: "https://images.unsplash.com/photo-1517433367423-c7e5b0f35086?w=800",
    badge: "Verificado",
    price: "Desde 2€",
    location: "Figaredo",
    phone: "+34 985 345 678",
    whatsapp: "+34985345678",
    website: "dulcecarbon.es",
    email: "info@dulcecarbon.es",
    address: "Calle La Vega 7, Figaredo, Mieres",
    coordinates: { lat: 43.2319, lng: -5.7826 },
    verified: true,
    isNew: false,
    publishedAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000), // 10 días atrás
    userId: "user-3",
  },
  {
    id: "4",
    title: "Mesón La Estación",
    category: "Restaurantes",
    subcategory: "Cocina tradicional",
    description: "Restaurante con amplia tradición minera que ofrece los mejores platos de la gastronomía asturiana. Especialidad en fabada, cachopo y carnes a la brasa.",
    imagePath: "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800",
    badge: "Popular",
    price: "Menú 15€",
    location: "Ujo",
    phone: "+34 985 456 789",
    whatsapp: "+34985456789",
    email: "info@mesonlaestacion.es",
    address: "Plaza de la Estación 3, Ujo, Mieres",
    coordinates: { lat: 43.1842, lng: -5.8103 },
    verified: true,
    isNew: false,
    publishedAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000), // 7 días atrás
    userId: "user-4"
  },
  {
    id: "5",
    title: "Papelería Valdecuna",
    category: "Productos",
    subcategory: "Papelería",
    description: "Todo en material escolar, artículos de oficina y regalos. Servicio de copistería, encuadernación y personalización de productos.",
    imagePath: "https://images.unsplash.com/photo-1576086213369-97a306d36557?w=800",
    badge: "Nuevo",
    price: "Varios",
    location: "Valdecuna",
    phone: "+34 985 567 890",
    whatsapp: "+34985567890",
    website: "papeleriavaldecuna.es",
    email: "info@papeleriavaldecuna.es",
    address: "Calle Principal 9, Valdecuna, Mieres",
    coordinates: { lat: 43.2406, lng: -5.7631 },
    verified: false,
    isNew: true,
    publishedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000), // 2 días atrás
    userId: "user-5"
  },
  {
    id: "6",
    title: "Alimentación La Campana",
    category: "Productos",
    subcategory: "Alimentación",
    description: "Tienda de alimentación con productos frescos locales y una amplia selección de embutidos asturianos, conservas y productos gourmet. Charcutería tradicional.",
    imagePath: "https://images.unsplash.com/photo-1604719312566-8912e9c8a213?w=800",
    badge: null,
    price: "Varios",
    location: "Santa Cruz",
    phone: "+34 985 678 901",
    whatsapp: "+34985678901",
    website: "alimentacionlacampana.es",
    email: "info@alimentacionlacampana.es",
    address: "Calle Real 5, Santa Cruz, Mieres",
    coordinates: { lat: 43.2276, lng: -5.7968 },
    verified: true,
    isNew: false,
    publishedAt: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000), // 8 días atrás
    userId: "user-6"
  },
  {
    id: "7",
    title: "Estética Belleza Minera",
    category: "Servicios",
    subcategory: "Estética",
    description: "Centro de belleza y bienestar con tratamientos faciales, corporales, manicura, pedicura y depilación. Productos naturales y técnicas innovadoras.",
    imagePath: "https://images.unsplash.com/photo-1560750588-73207b1ef5b5?w=800",
    badge: null,
    price: "Desde 15€",
    location: "Santa Rosa",
    phone: "+34 985 789 012",
    whatsapp: "+34985789012",
    website: "bellezaminera.es",
    email: "citas@bellezaminera.es",
    address: "Avenida de Santa Rosa 12, Santa Rosa, Mieres",
    coordinates: { lat: 43.2418, lng: -5.7727 },
    verified: true,
    isNew: false,
    publishedAt: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000), // 12 días atrás
    userId: "user-7"
  },
  {
    id: "8",
    title: "Ferretería Minera",
    category: "Productos",
    subcategory: "Ferretería",
    description: "Todo tipo de herramientas, materiales de construcción, pintura y artículos para el hogar. Asesoramiento personalizado para proyectos de bricolaje y reformas.",
    imagePath: "https://images.unsplash.com/photo-1578496479531-29ff7a0f889a?w=800",
    badge: null,
    price: "Varios",
    location: "La Peña",
    phone: "+34 985 890 123",
    whatsapp: "+34985890123",
    email: "info@ferreteriaminera.es",
    website: "ferreteriaminera.es",
    address: "Carretera General 45, La Peña, Mieres",
    coordinates: { lat: 43.2355, lng: -5.7518 },
    verified: false,
    isNew: false,
    publishedAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000), // 6 días atrás
    userId: "user-8"
  },
  {
    id: "9",
    title: "Academia de Baile Astur",
    category: "Formación",
    subcategory: "Baile",
    description: "Escuela de baile con clases de danza tradicional asturiana, bailes de salón, flamenco y ritmos modernos. Grupos para todas las edades y niveles. Primera clase de prueba gratuita.",
    imagePath: "https://images.unsplash.com/photo-1504609773096-104ff2c73ba4?w=800",
    badge: "Popular",
    price: "35€/mes",
    location: "Santullano",
    phone: "+34 985 901 234",
    whatsapp: "+34985901234",
    website: "baileastur.es",
    email: "info@baileastur.es",
    address: "Plaza del Pueblo 3, Santullano, Mieres",
    coordinates: { lat: 43.2392, lng: -5.7889 },
    verified: true,
    isNew: false,
    publishedAt: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000), // 20 días atrás
    userId: "user-9"
  },
  {
    id: "10",
    title: "Hogar Decor Minero",
    category: "Productos",
    subcategory: "Decoración y Regalos",
    description: "Tienda de decoración para el hogar y artículos de regalo. Amplia variedad de complementos decorativos, lámparas, textiles y objetos artesanales con inspiración minera.",
    imagePath: "https://images.unsplash.com/photo-1513519245088-0e12902e5a38?w=800",
    badge: "Nuevo",
    price: "Desde 5€",
    location: "Loredo",
    phone: "+34 985 012 345",
    whatsapp: "+34985012345",
    website: "hogardecorminero.es",
    email: "info@hogardecorminero.es",
    address: "Calle Mayor 8, Loredo, Mieres",
    coordinates: { lat: 43.2326, lng: -5.7592 },
    verified: false,
    isNew: true,
    publishedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000), // 3 días atrás
    userId: "user-10"
  },
  {
    id: "11",
    title: "Sidreria La Rebollada",
    category: "Restaurantes",
    subcategory: "Sidrería",
    description: "Tradicional sidrería asturiana con amplia carta de platos típicos de la región. Especialidad en cachopo, fabada y carnes a la parrilla. Escanciado tradicional de sidra.",
    imagePath: "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800",
    badge: "Recomendado",
    price: "Menú 15€",
    location: "Rebollada",
    phone: "+34 985 123 456",
    whatsapp: "+34985123456",
    website: "sidreriarebollada.es",
    email: "reservas@sidreriarebollada.es",
    address: "Carretera General 23, Rebollada, Mieres",
    coordinates: { lat: 43.2291, lng: -5.7698 },
    verified: true,
    isNew: false,
    publishedAt: new Date(Date.now() - 25 * 24 * 60 * 60 * 1000), // 25 días atrás
    userId: "user-11"
  },
  {
    id: "12",
    title: "Academia de Idiomas Urbies",
    category: "Formación",
    subcategory: "Idiomas",
    description: "Centro de enseñanza de idiomas con clases de inglés, francés, alemán e italiano. Preparación para exámenes oficiales y clases para todas las edades y niveles.",
    imagePath: "https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=800",
    badge: "Certificado",
    price: "120€/mes",
    location: "Urbiés",
    phone: "+34 985 234 567",
    whatsapp: "+34985234567",
    website: "academiaidiomasurbies.es",
    email: "info@academiaidiomasurbies.es",
    address: "Plaza Mayor 6, Urbiés, Mieres",
    coordinates: { lat: 43.2124, lng: -5.7729 },
    verified: true,
    isNew: false,
    publishedAt: new Date(Date.now() - 18 * 24 * 60 * 60 * 1000), // 18 días atrás
    userId: "user-12"
  },
  {
    id: "13",
    title: "Farmacia Baíña",
    category: "Servicios",
    subcategory: "Farmacia",
    description: "Farmacia con servicios de asesoramiento farmacéutico, formulación magistral, dietotécnica y análisis clínicos. Productos de parafarmacia y cosmética.",
    imagePath: "https://images.unsplash.com/photo-1586015555751-631036962?w=800",
    badge: "Esencial",
    price: "Varios",
    location: "Baíña",
    phone: "+34 985 345 678",
    whatsapp: "+34985345678",
    website: "farmaciabaina.es",
    email: "info@farmaciabaina.es",
    address: "Calle Principal 10, Baíña, Mieres",
    coordinates: { lat: 43.2435, lng: -5.7913 },
    verified: true,
    isNew: false,
    publishedAt: new Date(Date.now() - 21 * 24 * 60 * 60 * 1000), // 21 días atrás
    userId: "user-13"
  },
  {
    id: "14",
    title: "Fruteria Gallegos",
    category: "Productos",
    subcategory: "Alimentación",
    description: "Frutería con productos frescos de temporada, verduras locales y frutos secos a granel. Servicio de entrega a domicilio en Mieres.",
    imagePath: "https://images.unsplash.com/photo-1542838132-92c53300491e?w=800",
    badge: null,
    price: "Varios",
    location: "Gallegos",
    phone: "+34 985 456 789",
    whatsapp: "+34985456789",
    website: "fruteriagallegos.es",
    email: "pedidos@fruteriagallegos.es",
    address: "Avenida Principal 5, Gallegos, Mieres",
    coordinates: { lat: 43.2159, lng: -5.8025 },
    verified: true,
    isNew: false,
    publishedAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000), // 14 días atrás
    userId: "user-14"
  },
  {
    id: "15",
    title: "Perfumería Seana",
    category: "Productos",
    subcategory: "Perfumería",
    description: "Tienda especializada en perfumes, cosmética y productos de belleza. Las mejores marcas nacionales e internacionales con asesoramiento personalizado.",
    imagePath: "https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=800",
    badge: "Exclusivo",
    price: "Desde 20€",
    location: "Seana",
    phone: "+34 985 567 890",
    whatsapp: "+34985567890",
    website: "perfumeriaseana.es",
    email: "info@perfumeriaseana.es",
    address: "Calle San José 12, Seana, Mieres",
    coordinates: { lat: 43.2372, lng: -5.7651 },
    verified: true,
    isNew: false,
    publishedAt: new Date(Date.now() - 16 * 24 * 60 * 60 * 1000), // 16 días atrás
    userId: "user-15"
  },
  {
    id: "16",
    title: "Agencia de Viajes Santa Cruz",
    category: "Servicios",
    subcategory: "Turismo",
    description: "Agencia de viajes con ofertas nacionales e internacionales, circuitos organizados y viajes a medida. Especialistas en turismo rural por Asturias.",
    imagePath: "https://images.unsplash.com/photo-1541474019392-1861cce57c32?w=800",
    badge: null,
    price: "Varios",
    location: "Santa Cruz",
    phone: "+34 985 678 901",
    whatsapp: "+34985678901",
    website: "viajesantacruz.es",
    email: "reservas@viajesantacruz.es",
    address: "Calle Real 8, Santa Cruz, Mieres",
    coordinates: { lat: 43.2281, lng: -5.7975 },
    verified: false,
    isNew: true,
    publishedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000), // 1 día atrás
    userId: "user-16"
  }
]
